export const genders = [
  { label: "Masculino", value: "male" },
  { label: "Feminino", value: "female" },
  { label: "Outro", value: "other" },
] as const

export const goals = [
  { label: "Condicionamento Físico", value: "conditioning" },
  { label: "Emagrecimento", value: "weightLoss" },
  { label: "Força", value: "strength" },
  { label: "Qualidade de Vida", value: "qualityOfLife" },
  { label: "Hipertrofia", value: "hypertrophy" },
] as const

export const experiences = [
  { label: "Iniciante", value: "beginner" },
  { label: "Básico", value: "basic" },
  { label: "Intermediário", value: "intermediate" },
  { label: "Avançado", value: "advanced" },
  { label: "Especialista", value: "expert" },
] as const

export const muscleGroups = [
  { label: "Adutores", value: "adductors" },
  { label: "Antebraços", value: "forearms" },
  { label: "Bíceps", value: "biceps" },
  { label: "Core", value: "core" },
  { label: "Corpo Inteiro", value: "fullBody" },
  { label: "Costas", value: "back" },
  { label: "Glúteos", value: "glutes" },
  { label: "Lombar", value: "lowerBack" },
  { label: "Ombros", value: "shoulders" },
  { label: "Panturrilhas", value: "calves" },
  { label: "Peito", value: "chest" },
  { label: "Posteriores de Coxa", value: "hamstrings" },
  { label: "Quadríceps", value: "quadriceps" },
  { label: "Tríceps", value: "triceps" },
] as const

export const muscles = [
  { label: "Adutor do Polegar", value: "thumbAdductor" },
  { label: "Adutores", value: "adductors" },
  { label: "Adutores do Quadril", value: "hipAdductors" },
  { label: "Ancôneo", value: "anconeus" },
  { label: "Antebraços", value: "forearms" },
  { label: "Bíceps", value: "biceps" },
  { label: "Bíceps Braquial", value: "bicepsBrachii" },
  { label: "Braquial", value: "brachialis" },
  { label: "Braquiorradial", value: "brachioradialis" },
  { label: "Core", value: "core" },
  { label: "Deltoide Anterior", value: "anteriorDeltoid" },
  { label: "Deltoide Lateral", value: "lateralDeltoid" },
  { label: "Deltoide Posterior", value: "posteriorDeltoid" },
  { label: "Deltoides", value: "deltoids" },
  { label: "Eretores", value: "erectors" },
  { label: "Eretores da Coluna", value: "spinalErectors" },
  {
    label: "Estabilizadores do Tornozelo",
    value: "ankleStabilizers",
  },
  { label: "Extensor Radial do Carpo", value: "extensorCarpiRadialis" },
  { label: "Extensores do Antebraço", value: "forearmExtensors" },
  { label: "Extensores do Punho", value: "wristExtensors" },
  { label: "Extensores dos Dedos", value: "fingerExtensors" },
  { label: "Flexor Radial", value: "radialFlexor" },
  { label: "Flexores do Punho", value: "wristFlexors" },
  { label: "Flexores do Quadril", value: "hipFlexors" },
  { label: "Flexores dos Dedos", value: "fingerFlexors" },
  {
    label: "Flexores e Extensores do Antebraço",
    value: "forearmFlexorsAndExtensors",
  },
  {
    label: "Flexores e Extensores do Punho",
    value: "wristFlexorsAndExtensors",
  },
  { label: "Gastrocnêmio", value: "gastrocnemius" },
  { label: "Glúteo Máximo", value: "gluteusMaximus" },
  { label: "Glúteo Médio", value: "gluteusMedius" },
  { label: "Glúteo Mínimo", value: "gluteusMinimus" },
  { label: "Glúteos", value: "glutes" },
  { label: "Grácil", value: "gracilis" },
  { label: "Infraespinal", value: "infraspinatus" },
  { label: "Isquiotibiais", value: "hamstrings" },
  { label: "Latíssimo", value: "latissimus" },
  { label: "Latíssimo do Dorso", value: "latissimusDorsi" },
  { label: "Levantador da Escápula", value: "levatorScapulae" },
  { label: "Multífidos", value: "multifidus" },
  { label: "Músculos da Mão", value: "handMuscles" },
  { label: "Músculos do Pé", value: "footMuscles" },
  { label: "Oblíquos", value: "obliques" },
  { label: "Ombros", value: "shoulders" },
  { label: "Panturrilhas", value: "calves" },
  { label: "Pectíneo", value: "pectineus" },
  { label: "Peitoral", value: "chest" },
  { label: "Peitoral Maior", value: "pectoralisMajor" },
  { label: "Peitoral Superior", value: "upperChest" },
  { label: "Posteriores", value: "posteriorChain" },
  { label: "Posteriores da Coxa", value: "posteriorThigh" },
  { label: "Pronador Quadrado", value: "pronatorQuadratus" },
  { label: "Pronador Redondo", value: "pronatorTeres" },
  { label: "Quadrado Lombar", value: "quadratusLumborum" },
  { label: "Quadríceps", value: "quadriceps" },
  { label: "Redondo Maior", value: "teresMajor" },
  { label: "Redondo Menor", value: "teresMinor" },
  { label: "Reto Abdominal", value: "rectusAbdominis" },
  { label: "Romboides", value: "rhomboids" },
  { label: "Rotadores Externos", value: "externalRotators" },
  { label: "Serrátil", value: "serratus" },
  { label: "Serrátil Anterior", value: "serratusAnterior" },
  { label: "Sóleo", value: "soleus" },
  { label: "Supinador", value: "supinator" },
  { label: "Supraespinal", value: "supraspinatus" },
  { label: "Tensor da Fáscia Lata", value: "tensorFasciaeLatae" },
  { label: "Tibial Anterior", value: "tibialisAnterior" },
  { label: "Transverso", value: "transverse" },
  { label: "Transverso do Abdome", value: "transverseAbdominis" },
  { label: "Trapézio", value: "trapezius" },
  { label: "Trapézio Inferior", value: "lowerTrapezius" },
  { label: "Trapézio Médio", value: "middleTrapezius" },
  {
    label: "Trapézio Médio e Inferior",
    value: "middleAndLowerTrapezius",
  },
  { label: "Trapézio Superior", value: "upperTrapezius" },
  { label: "Tríceps", value: "triceps" },
  { label: "Tríceps (Cabeça Longa)", value: "tricepsLongHead" },
  { label: "Tríceps Braquial", value: "tricepsBrachii" },
] as const

export const difficulties = [
  { label: "Fácil", value: "easy" },
  { label: "Moderada", value: "moderate" },
  { label: "Difícil", value: "hard" },
] as const

export const origins = [
  { label: "Padrão", value: "default" },
  { label: "Personalizado", value: "custom" },
] as const
