import { normalizeExerciseName } from "@/lib/exercises/normalize"
import type { ExerciseKind } from "@/lib/workouts/methodology/types"

// Tabela explícita de padrões dinâmicos conhecidos; sem inferência pelo nome/equipamento.
const compoundPatterns = [
  "Agachar",
  "Agachar com base ampla",
  "Agachar com carga anterior",
  "Agachar com suporte",
  "Agachar guiado",
  "Agachar lateral",
  "Agachar unilateral",
  "Avanço",
  "Avanço dinâmico",
  "Avanço lateral",
  "Avanço lateral deslizante",
  "Avanço reverso",
  "Dobradiça com base ampla",
  "Dobradiça de quadril",
  "Dobradiça e puxada do solo",
  "Dobradiça sentada",
  "Subida unilateral",
  "Empurrar com pernas",
  "Empurrar declinado",
  "Empurrar e estender cotovelos",
  "Empurrar horizontal fechado",
  "Empurrar horizontal",
  "Empurrar inclinado",
  "Empurrar unilateral",
  "Empurrar vertical",
  "Empurrar vertical com rotação",
  "Puxar horizontal",
  "Puxar horizontal inclinado",
  "Puxar horizontal unilateral",
  "Puxar vertical",
  "Puxar vertical unilateral",
]
const isolationPatterns = [
  "Abdução de ombro",
  "Abdução de quadril",
  "Abdução horizontal",
  "Abdução lateral",
  "Adução de quadril",
  "Adução diagonal",
  "Adução horizontal",
  "Adução inclinada",
  "Desvio radial",
  "Dorsiflexão",
  "Elevação escapular",
  "Elevação escapular em Y",
  "Enrolar carga",
  "Extensão acima da cabeça",
  "Extensão de cotovelo com braço atrás",
  "Extensão de cotovelo deitado",
  "Extensão de cotovelo",
  "Extensão de joelho em cadeia fechada",
  "Extensão de joelho",
  "Extensão de ombro",
  "Extensão de punho",
  "Extensão de quadril apoiada",
  "Extensão de quadril unilateral",
  "Extensão de quadril",
  "Extensão de tronco",
  "Extensão diagonal de cotovelo",
  "Extensão unilateral de cotovelo",
  "Extensão unilateral de quadril",
  "Flexão alternada de cotovelo",
  "Flexão com rotação",
  "Flexão de cotovelo alongada",
  "Flexão de cotovelo apoiada",
  "Flexão de cotovelo com braço atrás",
  "Flexão de cotovelo em pronação do tronco",
  "Flexão de cotovelo",
  "Flexão de joelho",
  "Flexão de ombro",
  "Flexão de punho",
  "Flexão de quadril com controle pélvico",
  "Flexão de quadril suspensa",
  "Flexão de tronco",
  "Flexão dos dedos",
  "Flexão excêntrica de joelho",
  "Flexão neutra de cotovelo",
  "Flexão plantar com joelhos flexionados",
  "Flexão plantar com quadril flexionado",
  "Flexão plantar em pé",
  "Flexão plantar sentado",
  "Flexão plantar unilateral",
  "Flexão plantar",
  "Flexão pronada de cotovelo",
  "Flexão segmentar controlada",
  "Flexão unilateral apoiada",
  "Flexão unilateral de joelho",
  "Pronação",
  "Puxar para o rosto",
  "Puxar vertical curto",
  "Retroversão pélvica",
  "Rotação de tronco",
  "Rotação diagonal",
  "Rotação externa",
  "Supinação",
]
const kinds = new Map<string, ExerciseKind>([
  ...compoundPatterns.map(
    pattern => [normalizeExerciseName(pattern), "compound"] as const
  ),
  ...isolationPatterns.map(
    pattern => [normalizeExerciseName(pattern), "isolation"] as const
  ),
])
export const classifyMovement = (pattern: string) =>
  kinds.get(normalizeExerciseName(pattern))
